---
title: "Homework #3"
subtitle: |
  3.3, 3.5, 3.8, 3.18, 3.26, 3.28, 3.30
author: "Hayden Atchley"
date: '`r format(Sys.Date(), "%e %B %Y")`'
mainfont: Gentium Book Basic
output:
  pdf_document:
    toc: false
    fig_caption: yes
    latex_engine: lualatex
fonsize: 11pt
tabstop: 2
editor_options: 
  chunk_output_type: console
---

# 3.3
If the crew were aware of whether seeding was conducted, they may have---consciously or not---changed their behaviors in a way that would influence the results.

# 3.5
Though there are several samples of dioxin levels in the Vietnam veterans that are substantially higher that in other veterans, these are all extreme outliers. Additionally, there are over 6 times as many observations in the former group, so the outliers represent an even smaller proportion of this group. Further analysis is required to determine if the difference is stastically significant.

# 3.8
The observations are not independent, but that is by design. The paired _t_-test is used in this case, since each observation is paired with another, related observation.

# 3.18

## a
The difference in means is _not_ resistant, as a dramatic change in one observation changes this statistic considerably.

## b
The average of the ranks for the trauma group minus the average of the ranks for the non-trauma group _is_ resistant, as a dramatic change in one observation would not change the rankings, and therefore the difference of their averages, very much if at all.

# 3.26
